# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pg_logicaldec.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13pg_logicaldec.proto\x12\x0b\x64\x65\x63oderbufs"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01"\xa7\x02\n\x0c\x44\x61tumMessage\x12\x13\n\x0b\x63olumn_name\x18\x01 \x01(\t\x12\x13\n\x0b\x63olumn_type\x18\x02 \x01(\x03\x12\x15\n\x0b\x64\x61tum_int32\x18\x03 \x01(\x05H\x00\x12\x15\n\x0b\x64\x61tum_int64\x18\x04 \x01(\x03H\x00\x12\x15\n\x0b\x64\x61tum_float\x18\x05 \x01(\x02H\x00\x12\x16\n\x0c\x64\x61tum_double\x18\x06 \x01(\x01H\x00\x12\x14\n\ndatum_bool\x18\x07 \x01(\x08H\x00\x12\x16\n\x0c\x64\x61tum_string\x18\x08 \x01(\tH\x00\x12\x15\n\x0b\x64\x61tum_bytes\x18\t \x01(\x0cH\x00\x12)\n\x0b\x64\x61tum_point\x18\n \x01(\x0b\x32\x12.decoderbufs.PointH\x00\x12\x17\n\rdatum_missing\x18\x0b \x01(\x08H\x00\x42\x07\n\x05\x64\x61tum"4\n\x08TypeInfo\x12\x10\n\x08modifier\x18\x01 \x02(\t\x12\x16\n\x0evalue_optional\x18\x02 \x02(\x08"\xee\x01\n\nRowMessage\x12\x16\n\x0etransaction_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63ommit_time\x18\x02 \x01(\x04\x12\r\n\x05table\x18\x03 \x01(\t\x12\x1b\n\x02op\x18\x04 \x01(\x0e\x32\x0f.decoderbufs.Op\x12,\n\tnew_tuple\x18\x05 \x03(\x0b\x32\x19.decoderbufs.DatumMessage\x12,\n\told_tuple\x18\x06 \x03(\x0b\x32\x19.decoderbufs.DatumMessage\x12+\n\x0cnew_typeinfo\x18\x07 \x03(\x0b\x32\x15.decoderbufs.TypeInfo*U\n\x02Op\x12\x14\n\x07UNKNOWN\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x12\t\n\x05\x42\x45GIN\x10\x03\x12\n\n\x06\x43OMMIT\x10\x04\x42\x33\n&io.debezium.connector.postgresql.protoB\x07PgProtoH\x01'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "pg_logicaldec_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"\n&io.debezium.connector.postgresql.protoB\007PgProtoH\001"
    )
    _globals["_OP"]._serialized_start = 660
    _globals["_OP"]._serialized_end = 745
    _globals["_POINT"]._serialized_start = 36
    _globals["_POINT"]._serialized_end = 65
    _globals["_DATUMMESSAGE"]._serialized_start = 68
    _globals["_DATUMMESSAGE"]._serialized_end = 363
    _globals["_TYPEINFO"]._serialized_start = 365
    _globals["_TYPEINFO"]._serialized_end = 417
    _globals["_ROWMESSAGE"]._serialized_start = 420
    _globals["_ROWMESSAGE"]._serialized_end = 658
# @@protoc_insertion_point(module_scope)
