mock_companies_data = {
    "results": [
        {
            "id": "7086461639",
            "properties": {
                "createdate": "2023-02-24T03:00:14.155Z",
                "domain": "hubspot.com",
                "hs_lastmodifieddate": "2023-02-24T03:00:26.696Z",
                "hs_object_id": "7086461639",
                "name": "Hubspot, Inc.",
            },
            "createdAt": "2023-02-24T03:00:14.155Z",
            "updatedAt": "2023-02-24T03:00:26.696Z",
            "archived": False,
        },
        {
            "id": "7086464459",
            "properties": {
                "createdate": "2023-02-24T03:25:40.027Z",
                "domain": "fda.gov",
                "hs_lastmodifieddate": "2023-02-24T03:25:53.252Z",
                "hs_object_id": "7086464459",
                "name": "U.S. Food and Drug Administration",
            },
            "createdAt": "2023-02-24T03:25:40.027Z",
            "updatedAt": "2023-02-24T03:25:53.252Z",
            "archived": False,
        },
    ]
}

mock_contacts_data = {
    "results": [
        {
            "id": "1",
            "properties": {
                "createdate": "2023-02-24T03:00:13.460Z",
                "email": "emailmaria@hubspot.com",
                "firstname": "Maria",
                "hs_object_id": "1",
                "lastmodifieddate": "2023-02-24T14:07:59.929Z",
                "lastname": "Johnson (Sample Contact)",
            },
            "createdAt": "2023-02-24T03:00:13.460Z",
            "updatedAt": "2023-02-24T14:07:59.929Z",
            "archived": False,
        },
        {
            "id": "51",
            "properties": {
                "createdate": "2023-02-24T03:00:13.789Z",
                "email": "bh@hubspot.com",
                "firstname": "Brian",
                "hs_object_id": "51",
                "lastmodifieddate": "2023-02-24T03:00:25.112Z",
                "lastname": "Halligan (Sample Contact)",
            },
            "createdAt": "2023-02-24T03:00:13.789Z",
            "updatedAt": "2023-02-24T03:00:25.112Z",
            "archived": False,
        },
    ],
}

mock_deals_data = {
    "results": [
        {
            "id": "6744192456",
            "properties": {
                "amount": "500",
                "closedate": None,
                "createdate": "2023-02-24T03:01:01.147Z",
                "dealname": "With Atul",
                "dealstage": "qualifiedtobuy",
                "hs_lastmodifieddate": "2023-02-24T03:01:01.711Z",
                "hs_object_id": "6744192456",
                "pipeline": "default",
            },
            "createdAt": "2023-02-24T03:01:01.147Z",
            "updatedAt": "2023-02-24T03:01:01.711Z",
            "archived": False,
        },
        {
            "id": "6744457152",
            "properties": {
                "amount": "3233",
                "closedate": None,
                "createdate": "2023-02-24T03:53:39.801Z",
                "dealname": "Yodoo Deal (2021-11-25)",
                "dealstage": "qualifiedtobuy",
                "hs_lastmodifieddate": "2023-02-24T03:53:43.118Z",
                "hs_object_id": "6744457152",
                "pipeline": "default",
            },
            "createdAt": "2023-02-24T03:53:39.801Z",
            "updatedAt": "2023-02-24T03:53:43.118Z",
            "archived": False,
        },
    ]
}

mock_products_data = {
    "results": [
        {
            "id": "1155995587",
            "properties": {
                "createdate": "2023-02-24T04:00:20.898Z",
                "description": "Inner Garment",
                "hs_lastmodifieddate": "2023-02-24T04:00:20.898Z",
                "hs_object_id": "1155995587",
                "name": "Jockey ineer",
                "price": "23",
            },
            "createdAt": "2023-02-24T04:00:20.898Z",
            "updatedAt": "2023-02-24T04:00:20.898Z",
            "archived": False,
        },
        {
            "id": "1156116944",
            "properties": {
                "createdate": "2023-02-24T04:04:14.269Z",
                "description": None,
                "hs_lastmodifieddate": "2023-02-24T04:04:14.269Z",
                "hs_object_id": "1156116944",
                "name": "Mayonnaise - Individual Pkg",
                "price": "60",
            },
            "createdAt": "2023-02-24T04:04:14.269Z",
            "updatedAt": "2023-02-24T04:04:14.269Z",
            "archived": False,
        },
    ]
}

mock_tickets_data = {
    "results": [
        {
            "id": "1075966440",
            "properties": {
                "content": "New Ticket",
                "createdate": "2023-01-15T05:00:00Z",
                "hs_lastmodifieddate": "2023-02-24T05:01:27.700Z",
                "hs_object_id": "1075966440",
                "hs_pipeline": "0",
                "hs_pipeline_stage": "1",
                "hs_ticket_category": None,
                "hs_ticket_priority": "HIGH",
                "subject": "Barry Smallridge",
            },
            "createdAt": "2023-01-15T05:00:00Z",
            "updatedAt": "2023-02-24T05:01:27.700Z",
            "archived": False,
        },
        {
            "id": "1075966441",
            "properties": {
                "content": "Updated Ticket",
                "createdate": "2022-12-04T05:00:00Z",
                "hs_lastmodifieddate": "2023-02-24T05:01:28.161Z",
                "hs_object_id": "1075966441",
                "hs_pipeline": "0",
                "hs_pipeline_stage": "4",
                "hs_ticket_category": None,
                "hs_ticket_priority": "HIGH",
                "subject": "Griffith Ticehurst",
            },
            "createdAt": "2022-12-04T05:00:00Z",
            "updatedAt": "2023-02-24T05:01:28.161Z",
            "archived": False,
        },
    ]
}

mock_quotes_data = {
    "results": [
        {
            "id": "70524908",
            "properties": {
                "hs_createdate": "2023-02-24T05:03:50.166Z",
                "hs_expiration_date": "2023-05-26T03:59:59.999Z",
                "hs_lastmodifieddate": "2023-02-24T05:03:50.923Z",
                "hs_object_id": "70524908",
                "hs_public_url_key": "dee8e054f6fd4f55aead6bd0811af068",
                "hs_status": "DRAFT",
                "hs_title": "New Quote",
            },
            "createdAt": "2023-02-24T05:03:50.166Z",
            "updatedAt": "2023-02-24T05:03:50.923Z",
            "archived": False,
        }
    ]
}


mock_contacts_with_history = {
    "results": [
        {
            "id": "1",
            "properties": {
                "address": None,
                "annualrevenue": None,
                "associatedcompanyid": None,
                "associatedcompanylastupdated": None,
                "city": "Brisbane",
                "closedate": None,
                "company": "HubSpot",
                "company_size": None,
                "country": None,
                "createdate": "2023-06-28T13:55:47.572Z",
                "currentlyinworkflow": None,
                "date_of_birth": None,
                "days_to_close": None,
                "degree": None,
                "email": "emailmaria@hubspot.com",
                "engagements_last_meeting_booked": None,
                "engagements_last_meeting_booked_campaign": None,
                "engagements_last_meeting_booked_medium": None,
                "engagements_last_meeting_booked_source": None,
                "fax": None,
                "field_of_study": None,
                "first_conversion_date": None,
                "first_conversion_event_name": None,
                "first_deal_created_date": "2023-07-01T21:28:00.771Z",
                "firstname": "Maria",
                "followercount": None,
                "gender": None,
                "graduation_date": None,
                "hs_additional_emails": None,
                "hs_all_accessible_team_ids": None,
                "hs_all_assigned_business_unit_ids": None,
                "hs_all_contact_vids": "1",
                "hs_all_owner_ids": None,
                "hs_all_team_ids": None,
                "hs_analytics_average_page_views": "0",
                "hs_analytics_first_referrer": None,
                "hs_analytics_first_timestamp": "2023-06-28T13:55:47.558Z",
                "hs_analytics_first_touch_converting_campaign": None,
                "hs_analytics_first_url": None,
                "hs_analytics_first_visit_timestamp": None,
                "hs_analytics_last_referrer": None,
                "hs_analytics_last_timestamp": None,
                "hs_analytics_last_touch_converting_campaign": None,
                "hs_analytics_last_url": None,
                "hs_analytics_last_visit_timestamp": None,
                "hs_analytics_num_event_completions": "0",
                "hs_analytics_num_page_views": "0",
                "hs_analytics_num_visits": "0",
                "hs_analytics_revenue": "0.0",
                "hs_analytics_source": "OFFLINE",
                "hs_analytics_source_data_1": "API",
                "hs_analytics_source_data_2": "sample-contact",
                "hs_avatar_filemanager_key": None,
                "hs_buying_role": None,
                "hs_calculated_form_submissions": None,
                "hs_calculated_merged_vids": None,
                "hs_calculated_mobile_number": None,
                "hs_calculated_phone_number": None,
                "hs_calculated_phone_number_area_code": None,
                "hs_calculated_phone_number_country_code": None,
                "hs_calculated_phone_number_region_code": None,
                "hs_clicked_linkedin_ad": None,
                "hs_content_membership_email": None,
                "hs_content_membership_email_confirmed": None,
                "hs_content_membership_follow_up_enqueued_at": None,
                "hs_content_membership_notes": None,
                "hs_content_membership_registered_at": None,
                "hs_content_membership_registration_domain_sent_to": None,
                "hs_content_membership_registration_email_sent_at": None,
                "hs_content_membership_status": None,
                "hs_conversations_visitor_email": None,
                "hs_count_is_unworked": None,
                "hs_count_is_worked": None,
                "hs_created_by_conversations": None,
                "hs_created_by_user_id": None,
                "hs_createdate": None,
                "hs_date_entered_customer": None,
                "hs_date_entered_evangelist": None,
                "hs_date_entered_lead": "2023-06-28T13:55:47.558Z",
                "hs_date_entered_marketingqualifiedlead": None,
                "hs_date_entered_opportunity": "2023-07-01T21:28:01.332Z",
                "hs_date_entered_other": None,
                "hs_date_entered_salesqualifiedlead": None,
                "hs_date_entered_subscriber": None,
                "hs_date_exited_customer": None,
                "hs_date_exited_evangelist": None,
                "hs_date_exited_lead": "2023-07-01T21:28:01.332Z",
                "hs_date_exited_marketingqualifiedlead": None,
                "hs_date_exited_opportunity": None,
                "hs_date_exited_other": None,
                "hs_date_exited_salesqualifiedlead": None,
                "hs_date_exited_subscriber": None,
                "hs_document_last_revisited": None,
                "hs_email_bad_address": None,
                "hs_email_bounce": None,
                "hs_email_click": None,
                "hs_email_customer_quarantined_reason": None,
                "hs_email_delivered": None,
                "hs_email_domain": "hubspot.com",
                "hs_email_first_click_date": None,
                "hs_email_first_open_date": None,
                "hs_email_first_reply_date": None,
                "hs_email_first_send_date": None,
                "hs_email_hard_bounce_reason": None,
                "hs_email_hard_bounce_reason_enum": None,
                "hs_email_is_ineligible": None,
                "hs_email_last_click_date": None,
                "hs_email_last_email_name": None,
                "hs_email_last_open_date": None,
                "hs_email_last_reply_date": None,
                "hs_email_last_send_date": None,
                "hs_email_open": None,
                "hs_email_optout": None,
                "hs_email_optout_193660790": None,
                "hs_email_optout_193660800": None,
                "hs_email_quarantined": None,
                "hs_email_quarantined_reason": None,
                "hs_email_recipient_fatigue_recovery_time": None,
                "hs_email_replied": None,
                "hs_email_sends_since_last_engagement": None,
                "hs_emailconfirmationstatus": None,
                "hs_facebook_ad_clicked": None,
                "hs_facebook_click_id": None,
                "hs_facebookid": None,
                "hs_feedback_last_nps_follow_up": None,
                "hs_feedback_last_nps_rating": None,
                "hs_feedback_last_survey_date": None,
                "hs_feedback_show_nps_web_survey": None,
                "hs_first_engagement_object_id": None,
                "hs_first_outreach_date": None,
                "hs_first_subscription_create_date": None,
                "hs_google_click_id": None,
                "hs_googleplusid": None,
                "hs_has_active_subscription": None,
                "hs_ip_timezone": None,
                "hs_is_contact": "true",
                "hs_is_unworked": "true",
                "hs_language": None,
                "hs_last_sales_activity_date": None,
                "hs_last_sales_activity_timestamp": None,
                "hs_last_sales_activity_type": None,
                "hs_lastmodifieddate": None,
                "hs_latest_meeting_activity": None,
                "hs_latest_sequence_ended_date": None,
                "hs_latest_sequence_enrolled": None,
                "hs_latest_sequence_enrolled_date": None,
                "hs_latest_sequence_finished_date": None,
                "hs_latest_sequence_unenrolled_date": None,
                "hs_latest_source": "OFFLINE",
                "hs_latest_source_data_1": "API",
                "hs_latest_source_data_2": "sample-contact",
                "hs_latest_source_timestamp": "2023-06-28T13:55:47.640Z",
                "hs_latest_subscription_create_date": None,
                "hs_lead_status": None,
                "hs_legal_basis": None,
                "hs_lifecyclestage_customer_date": None,
                "hs_lifecyclestage_evangelist_date": None,
                "hs_lifecyclestage_lead_date": "2023-06-28T13:55:47.558Z",
                "hs_lifecyclestage_marketingqualifiedlead_date": None,
                "hs_lifecyclestage_opportunity_date": "2023-07-01T21:28:01.332Z",
                "hs_lifecyclestage_other_date": None,
                "hs_lifecyclestage_salesqualifiedlead_date": None,
                "hs_lifecyclestage_subscriber_date": None,
                "hs_linkedin_ad_clicked": None,
                "hs_linkedinid": None,
                "hs_marketable_reason_id": "Sample Contact",
                "hs_marketable_reason_type": "SAMPLE_CONTACT",
                "hs_marketable_status": "true",
                "hs_marketable_until_renewal": "true",
                "hs_merged_object_ids": None,
                "hs_object_id": "1",
            },
            "propertiesWithHistory": {
                "city": [
                    {
                        "value": "Brisbane",
                        "timestamp": "2023-06-28T13:55:47.558Z",
                        "sourceType": "CONTACTS_WEB",
                        "sourceId": "sample-contact",
                    }
                ],
                "company": [
                    {
                        "value": "HubSpot",
                        "timestamp": "2023-06-28T13:55:47.558Z",
                        "sourceType": "CONTACTS_WEB",
                        "sourceId": "sample-contact",
                    }
                ],
                "createdate": [
                    {
                        "value": "2023-06-28T13:55:47.572Z",
                        "timestamp": "2023-06-28T13:55:47.572Z",
                        "sourceType": "API",
                        "sourceId": "sample-contact",
                    }
                ],
                "hs_analytics_first_timestamp": [
                    {
                        "value": "2023-06-28T13:55:47.558Z",
                        "timestamp": "2023-06-28T13:55:52.465Z",
                        "sourceType": "ANALYTICS",
                        "sourceId": "ContactAnalyticsDetailsUpdateWorker",
                    }
                ],
                "lastmodifieddate": [
                    {
                        "value": "2023-07-01T21:28:22.147Z",
                        "timestamp": "2023-07-01T21:28:22.147Z",
                        "sourceType": "AI_GROUP",
                    },
                    {
                        "value": "2023-07-01T21:28:01.332Z",
                        "timestamp": "2023-07-01T21:28:01.332Z",
                        "sourceType": "API",
                    },
                    {
                        "value": "2023-07-01T21:28:01.331Z",
                        "timestamp": "2023-07-01T21:28:01.331Z",
                        "sourceType": "CALCULATED",
                    },
                    {
                        "value": "2023-06-28T13:55:52.465Z",
                        "timestamp": "2023-06-28T13:55:52.465Z",
                        "sourceType": "API",
                    },
                    {
                        "value": "2023-06-28T13:55:48.435Z",
                        "timestamp": "2023-06-28T13:55:48.435Z",
                        "sourceType": "API",
                    },
                    {
                        "value": "2023-06-28T13:55:47.809Z",
                        "timestamp": "2023-06-28T13:55:47.809Z",
                        "sourceType": "API",
                    },
                    {
                        "value": "2023-06-28T13:55:47.572Z",
                        "timestamp": "2023-06-28T13:55:47.572Z",
                        "sourceType": "API",
                        "sourceId": "sample-contact",
                    },
                ],
            },
            "createdAt": "2023-06-28T13:55:47.572Z",
            "updatedAt": "2023-07-01T21:28:22.147Z",
            "archived": False,
            "associations": {
                "deals": {"results": [{"id": "8078784221", "type": "contact_to_deal"}]}
            },
        },
        {
            "id": "51",
            "properties": {
                "address": None,
                "annualrevenue": None,
                "associatedcompanyid": None,
                "associatedcompanylastupdated": None,
                "city": "Cambridge",
                "closedate": None,
                "company": "HubSpot",
                "company_size": None,
                "country": None,
                "createdate": "2023-06-28T13:55:47.881Z",
                "currentlyinworkflow": None,
                "date_of_birth": None,
                "days_to_close": None,
                "degree": None,
                "email": "thisisnewemail@hubspot.com",
                "engagements_last_meeting_booked": None,
                "engagements_last_meeting_booked_campaign": None,
                "engagements_last_meeting_booked_medium": None,
                "engagements_last_meeting_booked_source": None,
                "fax": None,
                "field_of_study": None,
                "first_conversion_date": None,
                "first_conversion_event_name": None,
                "first_deal_created_date": "2023-07-01T21:28:00.771Z",
                "firstname": "Brian",
                "followercount": None,
                "gender": None,
                "graduation_date": None,
                "hs_additional_emails": None,
                "hs_all_accessible_team_ids": None,
                "hs_all_assigned_business_unit_ids": None,
                "hs_all_contact_vids": "51",
                "hs_all_owner_ids": None,
                "hs_all_team_ids": None,
                "hs_analytics_average_page_views": "0",
                "hs_object_id": "1",
            },
            "propertiesWithHistory": {
                "address": [],
                "annualrevenue": [],
                "associatedcompanyid": [],
                "associatedcompanylastupdated": [],
                "city": [
                    {
                        "value": "Cambridge",
                        "timestamp": "2023-06-28T13:55:47.558Z",
                        "sourceType": "CONTACTS_WEB",
                        "sourceId": "sample-contact",
                    }
                ],
                "closedate": [],
                "company": [
                    {
                        "value": "HubSpot",
                        "timestamp": "2023-06-28T13:55:47.558Z",
                        "sourceType": "CONTACTS_WEB",
                        "sourceId": "sample-contact",
                    }
                ],
                "company_size": [],
                "country": [],
                "createdate": [
                    {
                        "value": "2023-06-28T13:55:47.881Z",
                        "timestamp": "2023-06-28T13:55:47.881Z",
                        "sourceType": "API",
                        "sourceId": "sample-contact",
                    }
                ],
                "currentlyinworkflow": [],
                "date_of_birth": [],
                "days_to_close": [],
                "degree": [],
                "email": [
                    {
                        "value": "thisisnewemail@hubspot.com",
                        "timestamp": "2023-07-01T23:34:57.837Z",
                        "sourceType": "CRM_UI",
                        "sourceId": "userId:52368047",
                        "updatedByUserId": 52368047,
                    },
                    {
                        "value": "bh@hubspot.com",
                        "timestamp": "2023-06-28T13:55:47.558Z",
                        "sourceType": "API",
                        "sourceId": "sample-contact",
                    },
                ],
                "engagements_last_meeting_booked": [],
                "engagements_last_meeting_booked_campaign": [],
                "engagements_last_meeting_booked_medium": [],
                "engagements_last_meeting_booked_source": [],
                "fax": [],
                "field_of_study": [],
                "first_conversion_date": [],
                "first_conversion_event_name": [],
                "first_deal_created_date": [
                    {
                        "value": "2023-07-01T21:28:00.771Z",
                        "timestamp": "2023-07-01T21:28:01.398Z",
                        "sourceType": "CALCULATED",
                        "sourceId": "RollupProperties",
                    }
                ],
                "firstname": [
                    {
                        "value": "Brian",
                        "timestamp": "2023-06-28T13:55:47.558Z",
                        "sourceType": "CONTACTS_WEB",
                        "sourceId": "sample-contact",
                    }
                ],
                "followercount": [],
                "gender": [],
                "graduation_date": [],
                "hs_additional_emails": [],
                "hs_all_accessible_team_ids": [],
                "hs_all_assigned_business_unit_ids": [],
                "hs_all_contact_vids": [
                    {
                        "value": "51",
                        "timestamp": "2023-06-28T13:55:47.881Z",
                        "sourceType": "API",
                        "sourceId": "sample-contact",
                    }
                ],
                "hs_all_owner_ids": [],
                "hs_all_team_ids": [],
                "hs_analytics_average_page_views": [
                    {
                        "value": "0",
                        "timestamp": "2023-06-28T13:55:57.617Z",
                        "sourceType": "ANALYTICS",
                        "sourceId": "ContactAnalyticsDetailsUpdateWorker",
                    }
                ],
                "hs_analytics_first_referrer": [],
                "hs_analytics_first_timestamp": [
                    {
                        "value": "2023-06-28T13:55:47.881Z",
                        "timestamp": "2023-06-28T13:55:57.617Z",
                        "sourceType": "ANALYTICS",
                        "sourceId": "ContactAnalyticsDetailsUpdateWorker",
                    }
                ],
                "hs_analytics_first_touch_converting_campaign": [],
                "hs_analytics_first_url": [],
                "hs_analytics_first_visit_timestamp": [],
                "hs_analytics_last_referrer": [],
                "hs_analytics_last_timestamp": [],
                "hs_analytics_last_touch_converting_campaign": [],
                "hs_analytics_last_url": [],
                "hs_analytics_last_visit_timestamp": [],
                "hs_analytics_num_event_completions": [
                    {
                        "value": "0",
                        "timestamp": "2023-06-28T13:55:57.617Z",
                        "sourceType": "ANALYTICS",
                        "sourceId": "ContactAnalyticsDetailsUpdateWorker",
                    }
                ],
            },
            "createdAt": "2023-06-28T13:55:47.881Z",
            "updatedAt": "2023-07-01T23:34:57.865Z",
            "archived": False,
            "associations": {
                "deals": {"results": [{"id": "8078784221", "type": "contact_to_deal"}]}
            },
        },
    ]
}


mock_contacts_properties = {
    "results": [
        {"name": "company_size", "type": "string"},
        {"name": "date_of_birth", "type": "string"},
        {"name": "days_to_close", "type": "number"},
        {"name": "degree", "type": "string"},
        {"name": "field_of_study", "type": "string"},
        {"name": "first_conversion_date", "type": "datetime"},
        {"name": "first_conversion_event_name", "type": "string"},
        {"name": "first_deal_created_date", "type": "datetime"},
        {"name": "gender", "type": "string"},
        {"name": "graduation_date", "type": "datetime"},
        {"name": "hs_additional_emails", "type": "string"},
        {"name": "hs_all_assigned_business_unit_ids", "type": "string"},
        {"name": "hs_all_contact_vids", "type": "string"},
        {"name": "hs_analytics_first_touch_converting_campaign", "type": "string"},
        {"name": "hs_analytics_last_touch_converting_campaign", "type": "string"},
        {"name": "hs_avatar_filemanager_key", "type": "string"},
        {"name": "hs_buying_role", "type": "enumeration"},
        {"name": "hs_calculated_form_submissions", "type": "string"},
        {"name": "hs_calculated_merged_vids", "type": "string"},
        {"name": "hs_calculated_mobile_number", "type": "number"},
        {"name": "hs_calculated_phone_number", "type": "number"},
        {"name": "hs_calculated_phone_number_area_code", "type": "number"},
        {"name": "hs_calculated_phone_number_country_code", "type": "number"},
        {"name": "hs_calculated_phone_number_region_code", "type": "number"},
        {"name": "hs_clicked_linkedin_ad", "type": "string"},
        {"name": "hs_content_membership_email", "type": "string"},
        {"name": "hs_content_membership_email_confirmed", "type": "string"},
        {"name": "hs_content_membership_follow_up_enqueued_at", "type": "datetime"},
        {"name": "hs_content_membership_notes", "type": "string"},
        {"name": "hs_content_membership_registered_at", "type": "datetime"},
        {"name": "hs_content_membership_registration_domain_sent_to", "type": "string"},
        {
            "name": "hs_content_membership_registration_email_sent_at",
            "type": "datetime",
        },
        {"name": "hs_content_membership_status", "type": "enumeration"},
        {"name": "hs_conversations_visitor_email", "type": "string"},
        {"name": "hs_count_is_unworked", "type": "number"},
        {"name": "hs_count_is_worked", "type": "number"},
        {"name": "hs_created_by_conversations", "type": "string"},
        {"name": "hs_created_by_user_id", "type": "string"},
        {"name": "hs_createdate", "type": "string"},
        {"name": "hs_date_entered_customer", "type": "string"},
        {"name": "hs_date_entered_evangelist", "type": "string"},
        {"name": "hs_date_entered_lead", "type": "datetime"},
        {"name": "hs_date_entered_marketingqualifiedlead", "type": "datetime"},
        {"name": "hs_date_entered_opportunity", "type": "datetime"},
        {"name": "hs_date_entered_other", "type": "datetime"},
        {"name": "hs_date_entered_salesqualifiedlead", "type": "datetime"},
        {"name": "hs_date_entered_subscriber", "type": "datetime"},
        {"name": "hs_date_exited_customer", "type": "datetime"},
        {"name": "hs_date_exited_evangelist", "type": "datetime"},
        {"name": "hs_date_exited_lead", "type": "datetime"},
        {"name": "hs_date_exited_marketingqualifiedlead", "type": "datetime"},
        {"name": "hs_date_exited_opportunity", "type": "datetime"},
        {"name": "hs_date_exited_other", "type": "datetime"},
        {"name": "hs_date_exited_salesqualifiedlead", "type": "datetime"},
        {"name": "hs_date_exited_subscriber", "type": "datetime"},
        {"name": "hs_document_last_revisited", "type": "string"},
        {"name": "hs_email_bad_address", "type": "string"},
        {"name": "hs_email_customer_quarantined_reason", "type": "string"},
        {"name": "hs_email_domain", "type": "string"},
        {"name": "hs_email_hard_bounce_reason", "type": "string"},
        {"name": "hs_email_hard_bounce_reason_enum", "type": "number"},
        {"name": "hs_email_quarantined", "type": "string"},
        {"name": "hs_email_quarantined_reason", "type": "string"},
        {"name": "hs_email_recipient_fatigue_recovery_time", "type": "string"},
        {"name": "hs_email_sends_since_last_engagement", "type": "string"},
        {"name": "hs_emailconfirmationstatus", "type": "enumeration"},
        {"name": "hs_facebook_ad_clicked", "type": "string"},
        {"name": "hs_facebook_click_id", "type": "string"},
        {"name": "hs_facebookid", "type": "string"},
        {"name": "hs_feedback_last_nps_follow_up", "type": "string"},
        {"name": "hs_feedback_last_nps_rating", "type": "string"},
        {"name": "hs_feedback_last_survey_date", "type": "datetime"},
        {"name": "hs_feedback_show_nps_web_survey", "type": "string"},
        {"name": "hs_first_engagement_object_id", "type": "string"},
        {"name": "hs_first_outreach_date", "type": "datetime"},
        {"name": "hs_first_subscription_create_date", "type": "datetime"},
        {"name": "hs_google_click_id", "type": "string"},
        {"name": "hs_googleplusid", "type": "string"},
        {"name": "hs_has_active_subscription", "type": "bool"},
        {"name": "hs_ip_timezone", "type": "string"},
        {"name": "hs_is_contact", "type": "bool"},
        {"name": "hs_is_unworked", "type": "bool"},
        {"name": "hs_last_sales_activity_date", "type": "datetime"},
        {"name": "hs_last_sales_activity_timestamp", "type": "datetime"},
        {"name": "hs_last_sales_activity_type", "type": "enumeration"},
        {"name": "hs_lastmodifieddate", "type": "string"},
        {"name": "hs_latest_sequence_ended_date", "type": "datetime"},
        {"name": "hs_latest_sequence_enrolled", "type": "string"},
        {"name": "hs_latest_sequence_enrolled_date", "type": "datetime"},
        {"name": "hs_latest_sequence_finished_date", "type": "datetime"},
        {"name": "hs_latest_sequence_unenrolled_date", "type": "datetime"},
        {"name": "hs_latest_source_timestamp", "type": "datetime"},
        {"name": "hs_latest_subscription_create_date", "type": "datetime"},
        {"name": "hs_lead_status", "type": "enumeration"},
        {"name": "hs_legal_basis", "type": "enumeration"},
        {"name": "hs_linkedin_ad_clicked", "type": "string"},
        {"name": "hs_linkedinid", "type": "string"},
        {"name": "hs_marketable_reason_id", "type": "string"},
        {"name": "hs_marketable_reason_type", "type": "enumeration"},
        {"name": "hs_marketable_status", "type": "enumeration"},
        {"name": "hs_marketable_until_renewal", "type": "string"},
        {"name": "hs_merged_object_ids", "type": "string"},
        {"name": "hs_object_id", "type": "string"},
        {"name": "hs_pinned_engagement_id", "type": "string"},
        {"name": "hs_pipeline", "type": "string"},
        {"name": "hs_predictivecontactscore_v2", "type": "number"},
        {"name": "hs_predictivescoringtier", "type": "string"},
        {"name": "hs_read_only", "type": "string"},
        {"name": "hs_sa_first_engagement_date", "type": "datetime"},
        {"name": "hs_sa_first_engagement_descr", "type": "string"},
        {"name": "hs_sa_first_engagement_object_type", "type": "enumeration"},
        {"name": "hs_sales_email_last_clicked", "type": "string"},
        {"name": "hs_sales_email_last_opened", "type": "string"},
        {
            "name": "hs_searchable_calculated_international_mobile_number",
            "type": "number",
        },
        {
            "name": "hs_searchable_calculated_international_phone_number",
            "type": "number",
        },
        {"name": "hs_searchable_calculated_mobile_number", "type": "number"},
        {"name": "hs_searchable_calculated_phone_number", "type": "number"},
        {"name": "hs_sequences_actively_enrolled_count", "type": "number"},
        {"name": "hs_sequences_enrolled_count", "type": "number"},
        {"name": "hs_sequences_is_enrolled", "type": "string"},
        {"name": "hs_source_object_id", "type": "enumeration"},
        {"name": "hs_source_portal_id", "type": "enumeration"},
        {"name": "hs_testpurge", "type": "string"},
        {"name": "hs_testrollback", "type": "string"},
        {"name": "hs_time_between_contact_creation_and_deal_close", "type": "string"},
        {
            "name": "hs_time_between_contact_creation_and_deal_creation",
            "type": "string",
        },
        {"name": "hs_time_in_customer", "type": "string"},
        {"name": "hs_time_in_evangelist", "type": "string"},
        {"name": "hs_time_in_lead", "type": "string"},
        {"name": "hs_time_in_marketingqualifiedlead", "type": "string"},
        {"name": "hs_time_in_opportunity", "type": "string"},
        {"name": "hs_time_in_other", "type": "string"},
        {"name": "hs_time_in_salesqualifiedlead", "type": "string"},
        {"name": "hs_time_in_subscriber", "type": "string"},
        {"name": "hs_time_to_first_engagement", "type": "string"},
        {"name": "hs_time_to_move_from_lead_to_customer", "type": "string"},
        {
            "name": "hs_time_to_move_from_marketingqualifiedlead_to_customer",
            "type": "string",
        },
        {"name": "hs_time_to_move_from_opportunity_to_customer", "type": "string"},
        {
            "name": "hs_time_to_move_from_salesqualifiedlead_to_customer",
            "type": "string",
        },
        {"name": "hs_time_to_move_from_subscriber_to_customer", "type": "string"},
        {"name": "hs_timezone", "type": "string"},
        {"name": "hs_twitterid", "type": "string"},
        {"name": "hs_unique_creation_key", "type": "string"},
        {"name": "hs_updated_by_user_id", "type": "string"},
        {"name": "hs_user_ids_of_all_notification_followers", "type": "string"},
        {"name": "hs_user_ids_of_all_notification_unfollowers", "type": "string"},
        {"name": "hs_user_ids_of_all_owners", "type": "string"},
        {"name": "hs_was_imported", "type": "string"},
        {"name": "hs_whatsapp_phone_number", "type": "number"},
        {"name": "hubspot_owner_assigneddate", "type": "string"},
        {"name": "ip_city", "type": "string"},
        {"name": "ip_country", "type": "number"},
        {"name": "ip_country_code", "type": "number"},
        {"name": "ip_latlon", "type": "string"},
        {"name": "ip_state", "type": "string"},
        {"name": "ip_state_code", "type": "string"},
        {"name": "ip_zipcode", "type": "string"},
        {"name": "job_function", "type": "string"},
        {"name": "lastmodifieddate", "type": "string"},
        {"name": "marital_status", "type": "enumeration"},
        {"name": "military_status", "type": "enumeration"},
        {"name": "num_associated_deals", "type": "number"},
        {"name": "num_conversion_events", "type": "number"},
        {"name": "num_unique_conversion_events", "type": "number"},
        {"name": "recent_conversion_date", "type": "datetime"},
        {"name": "recent_conversion_event_name", "type": "string"},
        {"name": "recent_deal_amount", "type": "number"},
        {"name": "recent_deal_close_date", "type": "datetime"},
        {"name": "relationship_status", "type": "enumeration"},
        {"name": "school", "type": "string"},
        {"name": "seniority", "type": "string"},
        {"name": "start_date", "type": "datetime"},
        {"name": "total_revenue", "type": "number"},
        {"name": "work_email", "type": "string"},
        {"name": "firstname", "type": "string"},
        {"name": "hs_analytics_first_url", "type": "string"},
        {"name": "hs_email_delivered", "type": "string"},
        {"name": "hs_email_optout_193660790", "type": "bool"},
        {"name": "hs_email_optout_193660800", "type": "bool"},
        {"name": "twitterhandle", "type": "string"},
        {"name": "currentlyinworkflow", "type": "string"},
        {"name": "followercount", "type": "number"},
        {"name": "hs_analytics_last_url", "type": "string"},
        {"name": "hs_email_open", "type": "string"},
        {"name": "lastname", "type": "string"},
        {"name": "hs_analytics_num_page_views", "type": "number"},
        {"name": "hs_email_click", "type": "string"},
        {"name": "salutation", "type": "string"},
        {"name": "twitterprofilephoto", "type": "string"},
        {"name": "email", "type": "string"},
        {"name": "hs_analytics_num_visits", "type": "number"},
        {"name": "hs_email_bounce", "type": "string"},
        {"name": "hs_persona", "type": "enumeration"},
        {"name": "hs_social_last_engagement", "type": "string"},
        {"name": "hs_analytics_num_event_completions", "type": "number"},
        {"name": "hs_email_optout", "type": "bool"},
        {"name": "hs_social_twitter_clicks", "type": "string"},
        {"name": "mobilephone", "type": "string"},
        {"name": "phone", "type": "string"},
        {"name": "fax", "type": "string"},
        {"name": "hs_analytics_first_timestamp", "type": "datetime"},
        {"name": "hs_email_last_email_name", "type": "string"},
        {"name": "hs_email_last_send_date", "type": "datetime"},
        {"name": "hs_social_facebook_clicks", "type": "string"},
        {"name": "address", "type": "string"},
        {"name": "engagements_last_meeting_booked", "type": "string"},
        {"name": "engagements_last_meeting_booked_campaign", "type": "string"},
        {"name": "engagements_last_meeting_booked_medium", "type": "string"},
        {"name": "engagements_last_meeting_booked_source", "type": "enumeration"},
        {"name": "hs_analytics_first_visit_timestamp", "type": "datetime"},
        {"name": "hs_email_last_open_date", "type": "datetime"},
        {"name": "hs_latest_meeting_activity", "type": "string"},
        {"name": "hs_sales_email_last_replied", "type": "string"},
        {"name": "hs_social_linkedin_clicks", "type": "string"},
        {"name": "hubspot_owner_id", "type": "string"},
        {"name": "notes_last_contacted", "type": "string"},
        {"name": "notes_last_updated", "type": "string"},
        {"name": "notes_next_activity_date", "type": "datetime"},
        {"name": "num_contacted_notes", "type": "number"},
        {"name": "num_notes", "type": "number"},
        {"name": "owneremail", "type": "string"},
        {"name": "ownername", "type": "string"},
        {"name": "surveymonkeyeventlastupdated", "type": "string"},
        {"name": "webinareventlastupdated", "type": "string"},
        {"name": "city", "type": "string"},
        {"name": "hs_analytics_last_timestamp", "type": "datetime"},
        {"name": "hs_email_last_click_date", "type": "datetime"},
        {"name": "hs_social_google_plus_clicks", "type": "string"},
        {"name": "hubspot_team_id", "type": "string"},
        {"name": "linkedinbio", "type": "string"},
        {"name": "twitterbio", "type": "string"},
        {"name": "hs_all_owner_ids", "type": "string"},
        {"name": "hs_analytics_last_visit_timestamp", "type": "datetime"},
        {"name": "hs_email_first_send_date", "type": "datetime"},
        {"name": "hs_social_num_broadcast_clicks", "type": "number"},
        {"name": "state", "type": "string"},
        {"name": "hs_all_team_ids", "type": "string"},
        {"name": "hs_analytics_source", "type": "enumeration"},
        {"name": "hs_email_first_open_date", "type": "datetime"},
        {"name": "hs_latest_source", "type": "enumeration"},
        {"name": "zip", "type": "string"},
        {"name": "country", "type": "number"},
        {"name": "hs_all_accessible_team_ids", "type": "string"},
        {"name": "hs_analytics_source_data_1", "type": "enumeration"},
        {"name": "hs_email_first_click_date", "type": "datetime"},
        {"name": "hs_latest_source_data_1", "type": "enumeration"},
        {"name": "linkedinconnections", "type": "string"},
        {"name": "hs_analytics_source_data_2", "type": "enumeration"},
        {"name": "hs_email_is_ineligible", "type": "string"},
        {"name": "hs_language", "type": "string"},
        {"name": "hs_latest_source_data_2", "type": "enumeration"},
        {"name": "kloutscoregeneral", "type": "number"},
        {"name": "hs_analytics_first_referrer", "type": "string"},
        {"name": "hs_email_first_reply_date", "type": "datetime"},
        {"name": "jobtitle", "type": "string"},
        {"name": "photo", "type": "string"},
        {"name": "hs_analytics_last_referrer", "type": "string"},
        {"name": "hs_email_last_reply_date", "type": "datetime"},
        {"name": "message", "type": "string"},
        {"name": "closedate", "type": "string"},
        {"name": "hs_analytics_average_page_views", "type": "string"},
        {"name": "hs_email_replied", "type": "string"},
        {"name": "hs_analytics_revenue", "type": "number"},
        {"name": "hs_lifecyclestage_lead_date", "type": "datetime"},
        {"name": "hs_lifecyclestage_marketingqualifiedlead_date", "type": "datetime"},
        {"name": "hs_lifecyclestage_opportunity_date", "type": "datetime"},
        {"name": "lifecyclestage", "type": "enumeration"},
        {"name": "hs_lifecyclestage_salesqualifiedlead_date", "type": "datetime"},
        {"name": "createdate", "type": "string"},
        {"name": "hs_lifecyclestage_evangelist_date", "type": "datetime"},
        {"name": "hs_lifecyclestage_customer_date", "type": "datetime"},
        {"name": "hubspotscore", "type": "number"},
        {"name": "company", "type": "string"},
        {"name": "hs_lifecyclestage_subscriber_date", "type": "datetime"},
        {"name": "hs_lifecyclestage_other_date", "type": "datetime"},
        {"name": "website", "type": "string"},
        {"name": "numemployees", "type": "number"},
        {"name": "annualrevenue", "type": "number"},
        {"name": "industry", "type": "string"},
        {"name": "associatedcompanyid", "type": "string"},
        {"name": "associatedcompanylastupdated", "type": "string"},
        {"name": "hs_predictivecontactscorebucket", "type": "number"},
        {"name": "hs_predictivecontactscore", "type": "number"},
    ]
}
