
name: get changed pipelines

on:
  workflow_call:

jobs:
  get_changed_pipelines:
    runs-on: ubuntu-latest
    outputs:
      pipelines_list: ${{ steps.get_changed_pipelines.outputs.pipelines_list }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed pipelines
        id: get_changed_pipelines
        run: |
          echo "base.sha: ${{ github.event.pull_request.base.sha }}"
          echo "head.sha: ${{ github.event.pull_request.head.sha }}"

          raw_changed_pipelines=$(
            git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} \
              | grep '^pipelines/' || true
          )

          echo $raw_changed_pipelines

          if [ -z "$raw_changed_pipelines" ]; then
            echo "No changed pipelines. Skipping tests."
          else
            changed_pipelines=$(echo "$raw_changed_pipelines" \
              | sed -E 's/^pipelines\/([^/]+)\/[^/]+$/\1/; s/^pipelines\/(.*)_pipeline\.py$/\1/' \
              | sort -u \
              | tr '\n' ' '
            )
            echo "Changed pipelines: $changed_pipelines"
          fi
          echo "pipelines_list=$changed_pipelines" >> $GITHUB_OUTPUT
