
name: lint

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  run_lint:
    name: Runs mypy, flake and bandit
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8.x", "3.9.x", "3.10.x", "3.11.x"]
    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: dlt-pipelines/.venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: make dev

      - name: Run lint
        run: make lint

  matrix_job_required_check:
    name: Runs mypy, flake and bandit
    needs: run_lint
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check matrix job results
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "One or more matrix job tests failed or were cancelled. You may need to re-run them." && exit 1