
name: lint

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  run_lint:
    name: Runs mypy, flake and bandit
    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8.x"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: dlt-pipelines/.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction --all-extras

      - name: Run lint
        run: make lint
